name: Run tests automatically

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: |
            .pytest_cache
            __pycache__
          key: ${{ runner.os }}-pytest-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pytest-

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest
